version: '3.3'
services:
  r:
    platform: linux/amd64
    build: .
    ports:
      - "8810:8787"
    volumes:
      - .:/home/rstudio/aquadata.data.mapping
    environment:
      DISABLE_AUTH: "true"
