name: Update Dataverse metadata

on:
  push:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build-container:
    name: Build R container
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build image with cache
        id: build-docker
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: r-update-dataverse-metadata
          dockerfile: Dockerfile.prod

  update-raw-metadata:
    name: Update raw metadata
    needs: build-container
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/worldfishcenter/aquadata.data.mapping/r-update-dataverse-metadata
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clean old raw metadata
        run: rm -rf inst/dataverse_raw/*
      - run: git config --global --add safe.directory /__w/aquadata.data.mapping/aquadata.data.mapping
      - name: Download dataverse raw metadata
        run: Rscript -e 'aquadata.data.mapping::get_dataverse_metadata()'
      - name: Commit raw metadata
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: inst/dataverse_raw/*

  process-raw-metadata:
    name: Process raw metadata
    needs: update-raw-metadata
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/worldfishcenter/aquadata.data.mapping/r-update-dataverse-metadata
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: git config --global --add safe.directory /__w/aquadata.data.mapping/aquadata.data.mapping
      - name: Process raw metadata
        run: Rscript -e 'aquadata.data.mapping::process_raw_metadata()'
      - name: Commit processed metadata
        run: |
          git config --global user.email "lorenzo.longobardi@gmail.com.com"
          git config --global user.name "langbart"
          git pull
          git add data/
          git commit -m "Commit processed metadata"
          git push
          git config --global user.name "langbart"
