name: Update Dataverse metadata

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-container:
    name: Build R container
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image with cache
        id: build-docker
        uses: whoan/docker-build-with-cache-action@v5
      - name: Install Miniconda
        run: |
          Rscript -e "reticulate::install_miniconda()"
          Rscript -e "reticulate::conda_create('r-reticulate', packages = c('python==3.8.13'))"
        with:
          username: $GITHUB_ACTOR
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          image_name: r-update-dataverse-metadata
          dockerfile: Dockerfile.prod

  update-data:
    name: Update organizations metadata
    needs: build-container
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/worldfishcenter/aquadata.data.mapping/r-update-dataverse-metadata
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Call get_organization_metadata()
        run: Rscript -e 'aquadata.data.mapping::get_organization_metadata(organization = "CIAT")'
